### ISSUE TITLE
Publish SDK to Maven Central / jCenter

### ISSUE THREAD

**Issue by nitrico** [lokalise/lokalise-android-sdk#2]
I think it would be nice if you publish the SDK to a repository so updates can be handled easier via Gradle without having to download the .aar file and place it inside the project manually.

Thanks :)

**Comment by DrParanoia** [comment]
Sure ;) We're already on it, will be available soon.

**Comment by nitrico** [comment]
Great 👍

**Comment by mmoczkowski** [comment]
Guys, any updates on this? I have 30+ dependencies in my projects and this is the only one I have to download manually.

**Comment by DrParanoia** [comment]
@mmoczkowski Most likely next week ;)

**Comment by DrParanoia** [comment]
@mmoczkowski @nitrico You can now include our SDK without downloading (via Maven). Please check the readme.
