### ISSUE TITLE
LokaliseSDK.updateTranslations() doesn't provide a callback

### ISSUE THREAD

**Issue by Tindaro85** [lokalise/lokalise-android-sdk#3]
Please expose a callback for LokaliseSDK.updateTranslations() .
As far as I understood this method is asynchronous so there is no way to exactly know when the translations have been updated after calling it.

Thanks

**Comment by DrParanoia** [comment]
Callbacks are now implemented in version 1.3.0 (docs are here https://lokalise.helpdocs.io/article/NAGqt96y1e-lokalise-android-sdk)
