### ISSUE TITLE
Incorrect LokaliseSDK.setPreRelease() function.

### ISSUE THREAD

**Issue by ramanbranavitski** [lokalise/lokalise-android-sdk#4]
Hi there. Was experimenting with you LokaliseSDK.setPreRelease() function and haven't noticed any changes in passing true/false as it's argument. 

```
public static void setPreRelease(boolean preRelease) {
        preRelease = preRelease;
    }
```
The code doesn't change internal variable because of lack of `this` keyword.
It would be great if you fix it. Thanks.

**Comment by DrParanoia** [comment]
The method works as expected. Looks like your piece of code got affected by the decompilation.
```
public static void setPreRelease(boolean preRelease) {
    LokaliseSDK.preRelease = preRelease;
}
```

**Comment by ramanbranavitski** [comment]
Thanks for explanation.
