### ISSUE TITLE
NoClassDefFoundError checkforVectorCompat

### ISSUE THREAD

**Issue by maddymanu** [lokalise/lokalise-android-sdk#6]
E/AndroidRuntime(29748): java.lang.NoClassDefFoundError: android.support.v7.widget.VectorEnabledTintResources
E/AndroidRuntime(29748): 	at co.lokalise.android.sdk.LokaliseSDK.checkForVectorCompat(LokaliseSDK.java:179)
E/AndroidRuntime(29748): 	at co.lokalise.android.sdk.LokaliseSDK.<init>(LokaliseSDK.java:82)
E/AndroidRuntime(29748): 	at co.lokalise.android.sdk.LokaliseSDK.init(LokaliseSDK.java:296)
E/AndroidRuntime(29748): 	at co.poynt.terminal.TerminalApplication.onCreate(TerminalApplication.java:32)
E/AndroidRuntime(29748): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime(29748): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
E/AndroidRuntime(29748): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime(29748): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime(29748): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(29748): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(29748): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(29748): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29748): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(29748): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(29748): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(29748): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by DrParanoia** [comment]
Currently our SDK implies that everyone is using AppCompat library when building applications. Might add a few checks, thanks.
